<?php
/**
 * Registers the WhatsApp consent field for block-based checkout and enqueues
 * the real-time cart tracker script on the checkout page.
 *
 * Uses the WooCommerce additional checkout fields API (WC 8.6+).
 * Falls back gracefully on older versions — classic checkout consent
 * is handled by CheckoutConsent instead.
 *
 * @package CartPinger\WooCommerce
 */

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

namespace CartPinger\WooCommerce;

/**
 * Class CheckoutFields
 */
final class CheckoutFields {

	/**
	 * Register hooks.
	 */
	public static function register(): void {
		add_action( 'woocommerce_init', array( self::class, 'registerFields' ) );
		add_action( 'wp_enqueue_scripts', array( self::class, 'enqueueBlockAssets' ) );
	}

	/**
	 * Register the WhatsApp consent checkbox in the block checkout order section.
	 *
	 * Only runs when the WooCommerce additional checkout fields API is available
	 * (introduced in WC 8.6). Silently skips on older installs.
	 */
	public static function registerFields(): void {
		if ( ! function_exists( 'woocommerce_register_additional_checkout_field' ) ) {
			return;
		}

		woocommerce_register_additional_checkout_field(
			array(
				'id'       => 'cartpinger/whatsapp_consent',
				'label'    => __( 'I agree to receive WhatsApp messages about my order and abandoned cart recovery.', 'cartpinger' ),
				'location' => 'order',
				'type'     => 'checkbox',
				'required' => false,
			)
		);
	}

	/**
	 * Enqueue the block checkout tracker script on the checkout page.
	 *
	 * Relies on the asset manifest generated by wp-scripts. Silently skips
	 * when the build artefact is absent (e.g. development without a build step).
	 */
	public static function enqueueBlockAssets(): void {
		if ( ! is_checkout() ) {
			return;
		}

		$asset_file = CARTPINGER_PLUGIN_DIR . 'assets/build/block-checkout-tracker.asset.php';
		if ( ! file_exists( $asset_file ) ) {
			return;
		}

		$asset = require $asset_file; // phpcs:ignore WordPressVIPMinimum.Files.IncludingFile.UsingVariable

		wp_enqueue_script(
			'cartpinger-block-tracker',
			CARTPINGER_PLUGIN_URL . 'assets/build/block-checkout-tracker.js',
			$asset['dependencies'],
			$asset['version'],
			true
		);

		wp_localize_script(
			'cartpinger-block-tracker',
			'cartpingerTracker',
			array(
				'apiUrl' => rest_url( 'cartpinger/v1/' ),
				'nonce'  => wp_create_nonce( 'wp_rest' ),
			)
		);
	}
}
